[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = true
test = "test"
script = "script"
broadcast = "broadcast"
cache_path = "cache"
remappings = [
    "@layerzerolabs/=lib/LayerZero-v2/packages/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/"
]

[rpc_endpoints]
ethereum = "${ETH_RPC_URL}"
arbitrum = "${ARBITRUM_RPC_URL}"
local = "http://127.0.0.1:8545"

[etherscan]
ethereum = { key = "${ETHERSCAN_API_KEY}" }
arbitrum = { key = "${ARBISCAN_API_KEY}" }

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true